### 1. Реєстрація нового користувача
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Dasha",
  "email": "dasha@example.com",
  "password": "qwerty123"
}

### 2. Логін
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "dasha@example.com",
  "password": "qwerty123"
}

# ⚠️ Скопіюйте accessToken з відповіді нижче і вставте в усі наступні запити замість {{accessToken}}

###

### 3. Отримання списку контактів
GET http://localhost:3000/contacts?page=1&perPage=5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDUxMWVlNjgzNmE2NjRlYTE2YTM3NCIsImlhdCI6MTc1ODkwMDY0NSwiZXhwIjoxNzU4OTAxNTQ1fQ.3wmq-kyLIxJMx0WYDs3MzPockfjRnbqaJr8S7KPX0qQ

### 4. Створення нового контакту
POST http://localhost:3000/contacts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDUxMWVlNjgzNmE2NjRlYTE2YTM3NCIsImlhdCI6MTc1ODkwMDY0NSwiZXhwIjoxNzU4OTAxNTQ1fQ.3wmq-kyLIxJMx0WYDs3MzPockfjRnbqaJr8S7KPX0qQ

{
  "name": "Ivan Petrov",
  "phoneNumber": "+380501234567",
  "email": "ivan.petrov@example.com",
  "isFavourite": true,
  "contactType": "work"
}

# ⚠️ Скопіюйте _id нового контакту з відповіді і вставте в наступні запити замість {{contactId}}

###

### 5. Отримання конкретного контакту
GET http://localhost:3000/contacts/68d6b1c46b68dde0dc769d01
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDUxMWVlNjgzNmE2NjRlYTE2YTM3NCIsImlhdCI6MTc1ODkwMDY0NSwiZXhwIjoxNzU4OTAxNTQ1fQ.3wmq-kyLIxJMx0WYDs3MzPockfjRnbqaJr8S7KPX0qQ

### 6. Оновлення контакту
PATCH http://localhost:3000/contacts/68d6b1c46b68dde0dc769d01
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDUxMWVlNjgzNmE2NjRlYTE2YTM3NCIsImlhdCI6MTc1ODkwMDY0NSwiZXhwIjoxNzU4OTAxNTQ1fQ.3wmq-kyLIxJMx0WYDs3MzPockfjRnbqaJr8S7KPX0qQ

{
  "phoneNumber": "+380501111111",
  "isFavourite": false
}

### 7. Видалення контакту
DELETE http://localhost:3000/contacts/68d6b1c46b68dde0dc769d01
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDUxMWVlNjgzNmE2NjRlYTE2YTM3NCIsImlhdCI6MTc1ODkwMDY0NSwiZXhwIjoxNzU4OTAxNTQ1fQ.3wmq-kyLIxJMx0WYDs3MzPockfjRnbqaJr8S7KPX0qQ

### 8. Рефреш токена
POST http://localhost:3000/auth/refresh
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDUxMWVlNjgzNmE2NjRlYTE2YTM3NCIsImlhdCI6MTc1ODkwMDY0NSwiZXhwIjoxNzU4OTAxNTQ1fQ.3wmq-kyLIxJMx0WYDs3MzPockfjRnbqaJr8S7KPX0qQ

### 9. Логаут
POST http://localhost:3000/auth/logout
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDUxMWVlNjgzNmE2NjRlYTE2YTM3NCIsImlhdCI6MTc1ODkwMDc2NCwiZXhwIjoxNzU4OTAxNjY0fQ.uUfY6V2KXkidrsr3ouBU5L6vWtSm7l7RmAyC0XQnw2I
