### Get first page (default perPage=10)
GET http://localhost:3000/contacts
Accept: application/json

###

### Get page 2 with 4 items per page
GET http://localhost:3000/contacts?page=2&perPage=4
Accept: application/json

###

### Get sorted by name descending
GET http://localhost:3000/contacts?sortBy=name&sortOrder=desc
Accept: application/json

###

### Filter by type = home and only favourites
GET http://localhost:3000/contacts?type=home&isFavourite=true
Accept: application/json

###

### Create a contact (valid)
POST http://localhost:3000/contacts
Content-Type: application/json
Accept: application/json

{
  "name": "Test User",
  "phoneNumber": "+380501234567",
  "email": "test@example.com",
  "contactType": "personal"
}

###

### Update contact (patch)
PATCH http://localhost:3000/contacts/68b889cd99d083f76299ca51
Content-Type: application/json

{
  "isFavourite": true
}



###

### Delete contact
DELETE http://localhost:3000/contacts/68b889cd99d083f76299ca51
Accept: application/json
